---
server:
   port: 8888
#application has been removed since spring 2.0
#security:
   #basic:
      #enabled: false
spring:
   security:
      user:
         name: root
         password: password
   cloud:
      config:
         server:
            git:
               uri: https://github.com/stobias2014/spring-cloudconfig-tx-tolls
               #username: uname
               #password: pass
               search-paths:
                  - 'station*'
               repos:
                  perf:
                     pattern:
                        - "*/perf"
                     uri: https://github.com/stobias2014/spring-cloudconfig-tx-tolls-perf
                     search-paths:
                        - 'station*'
                        
                   